services:
  sftp:
    image: linuxserver/openssh-server
    environment:
      - PUBLIC_KEY_FILE=/path/to/filesftp
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCpnjFhLnv67Nn892RpHcaxKOLmINrcssAYfGmrITcI06sQUqk8yXvuwi648uuPraawVGfMybbyZBBHyrKn/hdPQzG7HSj+U52wnaqtKKr22/7mEgBAom3OJyJZMTjWKTU7C/FhiQHv8Hi709tsuctky4xClmR7b2XrDhJHXsegGEoykIQLxI4kmJbKCrQsiTOzAH75fSEwmipnqHhDdl5ZIeEandvKHHSmJNtGll399y0hqS31zNTcwbNFckkfrAOmWU8rRo7R/XsVcdFOrM7cmpj/JdQ4tKYaEXiAQCHf/WHaRSy0SBclMy2Wl0ujXRTnNKG6/mrHAgPbNTPnjM+XCHtjSfOMhyAzve51lnbz2kNHGVV/m8OOch0LGWNH1JSn1UY12M+K42y1sZcB7+qvDXvz+q5l3d6vyN2FQJSnchYLPQpO9zK+tSJgb88bG8waU+c4NglKLjO3HwmZ+HuxcdANUZAsQ5LYwLqYLVRTZe7vJbuYSX7saRu3C30u9Q8= joavila@MX0C02FM4WMML85
      - USER_NAME=test
      - SUDO_ACCESS=true
    ports:
      - 2222:2222